name = "Developer"
description = "Para desarrolladores: recursos, red y contenedores"

[motd]
header = ""
footer = ""

[modules]
system = true
resources = true
weather = false
cowsay = false
network = true
containers = true
updates = false
logins = false
quote = false
calendar = true
services = false
logo = true
