name = "Minimal"
description = "Solo lo esencial: información del sistema y logo de la distro"

[motd]
header = ""
footer = ""

[modules]
system = true
resources = false
weather = false
cowsay = false
network = false
containers = false
updates = false
logins = false
quote = false
calendar = false
services = false
logo = true
